### ISSUE TITLE
release for --use-flag-height?

### ISSUE THREAD

**Issue by chance-nb** [ExperiBass/cli-pride-flags#23]
hi just wondering if you're gonna make a release for --use-flag-height; would be nice not to have to install from source for that

**Comment by 0xf0xx0** [comment]
ah yeah, ive been busy but ill try to get a release out this week :3

**Comment by chance-nb** [comment]
ty :3

**Comment by 0xf0xx0** [comment]
released :3 the commits will pop up here in the next couple hours once my forgejo syncs
